"""Changes the Input Type for the Step Photo

Revision ID: 39d185b113af
Revises: f5a645866aef
Create Date: 2026-05-11 11:33:03.913991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39d185b113af'
down_revision = 'f5a645866aef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('step', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.Text(), nullable=True))
        batch_op.drop_column('photo_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('step', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.VARCHAR(length=500), nullable=True))
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
