"""Changes the Input Type for the Cover Photo

Revision ID: 64f91cbb8327
Revises: 59542274e2fd
Create Date: 2026-05-10 23:44:23.975175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64f91cbb8327'
down_revision = '59542274e2fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image', sa.LargeBinary(), nullable=True))
        batch_op.drop_column('cover_image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image_url', sa.VARCHAR(length=500), nullable=True))
        batch_op.drop_column('cover_image')

    # ### end Alembic commands ###
