"""allow multiple reviews per user

Revision ID: 790a8bb74841
Revises: 53e1d53f1d3b
Create Date: 2026-05-14 12:38:21.498124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '790a8bb74841'
down_revision = '53e1d53f1d3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_review_author_recipe'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_review_author_recipe'), ['author_id', 'recipe_id'])

    # ### end Alembic commands ###
