"""Fixed the Recipe in the database so content can be added

Revision ID: f5a645866aef
Revises: 64f91cbb8327
Create Date: 2026-05-11 08:43:27.067841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5a645866aef'
down_revision = '64f91cbb8327'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.alter_column('cover_image',
               existing_type=sa.BLOB(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.alter_column('cover_image',
               existing_type=sa.Text(),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
